name: Check if the readme is up to date.

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v2

      - name: Check readme
        run: |
          ./scripts/update_readme.py --check
