name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      db:
        image: mongo:4.4.6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          pip install ".[all]"
      - name: Run pytest
        run: |
          pytest .
